--import later!
INSERT INTO users (id, email, nickname, password, image, created_at, updated_at) VALUES (1,"MJ@codestates.com", "MJ", "0000", "default.img", now(), now());
INSERT INTO users (id, email, nickname, password, image, created_at, updated_at) VALUES (2,"HJ@codestates.com", "HJ", "0000", "default.img", now(), now());
INSERT INTO users (id, email, nickname, password, image, created_at, updated_at) VALUES (3,"SW@codestates.com", "SW", "0000", "default.img", now(), now());
INSERT INTO users (id, email, nickname, password, image, created_at, updated_at) VALUES (4,"JH@codestates.com", "JH", "0000", "default.img", now(), now());

INSERT INTO article (id,title, image, comment, user_id) VALUES (1,"TEST1", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",1);
INSERT INTO article (id,title, image, comment, user_id) VALUES (2,"TEST2", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",2);
INSERT INTO article (id,title, image, comment, user_id) VALUES (3,"TEST3", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",3);
INSERT INTO article (id,title, image, comment, user_id) VALUES (4,"TEST1", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",1);
INSERT INTO article (id,title, image, comment, user_id) VALUES (5,"TEST2", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",2);
INSERT INTO article (id,title, image, comment, user_id) VALUES (6,"TEST3", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",3);
INSERT INTO article (id,title, image, comment, user_id) VALUES (7,"TEST1", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",1);
INSERT INTO article (id,title, image, comment, user_id) VALUES (8,"TEST2", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",2);
INSERT INTO article (id,title, image, comment, user_id) VALUES (9,"TEST3", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",3);
INSERT INTO article (id,title, image, comment, user_id) VALUES (10,"TEST1", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",1);
INSERT INTO article (id,title, image, comment, user_id) VALUES (11,"TEST2", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",2);
INSERT INTO article (id,title, image, comment, user_id) VALUES (12,"TEST3", "https://lh3.googleusercontent.com/proxy/e9mI6AvVBAKVC8pTIRoeCrZf6INl7MhIyIti4FioQrOk6TXBsAK-dhiwrKmnAKMKiVIAQW4PiJ8XGgQUBiQAORFYhdz8lQ3oD291qzdN_Fkd80iqyeRTe94bzfH9ytYyTDQQ6BRtMxlWjoXHFqCFN11uAoORThqrO9Jv","TEST content",3);